### ISSUE TITLE
Environment Variables do not seem to work

### ISSUE THREAD

**Issue by NotMyself** [rwtombaugh/serverless#1]
### Via Serverless CLI

1. Create function with the following serverless.yml
  ```yml
service: 
  name: webtasks-nodejs

provider:
  name: webtasks

environment:
  FOO: 'BAR'

functions:
  main:
    handler: handler

plugins:
  - '@webtask/serverless-webtasks'
  ```
2. Update the function to consume the env var
  ```javascript
'use strict';

module.exports = (context, cb) => {
    const message = `${process.env.FOO}: Go Serverless & Webtasks! Your function executed successfully!`
    console.log(message);
    cb(null, { message });
}
  ```
3. Deploy the function `serverless deploy`
4. Invoke the function `serverless invoke -f main`

## Result

```json
{
    "statusCode": 200,
    "body": "{\"message\":\"undefined: Go Serverless & Webtasks! Your function executed successfully!\"}"
}
```

## Expected Result

```json
{
    "statusCode": 200,
    "body": "{\"message\":\"BAR: Go Serverless & Webtasks! Your function executed successfully!\"}"
}
```
